= Qualitätsanforderungen
:navtitle: Qualität

In diesem Abschnitt geht es um die Qualitätsanforderungen, welche an lumidora gestellt werden.
Um Qualitätsanforderungen strukturiert zu erheben, helfen uns Qualitätsmodelle. Ein weitverbreitetes Qualitätsmodell ist der ISO 25010-Standard.

== Top 3 Qualitätsmerkmale dieses Projektes

. Hohe Ausgabequalität der generierten Inhalte
. Arbeitsaufträge die an den ai-assistenten gestellt werden, sollen erledigt werden. (Stabilität und Fehlertoleranz)
. Benutzerfreundliche Verwendung der einzelnen Generierungsmodule. Der Benutzer kann möglichst flexibel Inhalte generieren und die einzelnen Module des ai-assistenten ansprechen.

== Risiken
Eines der entscheidenen Risiken ist, das die erstellten Inhalte des ai-assistenten keine ausreichend hohe Qualität haben. Es wird vorausgesetzt,
das eingesetzte Open Source Tools, dessen aktuelle Ausgabequalität noch nicht ausreichend ist, in Zukunft ihre Qualität steigern können.

== Qualitätsszenarien

[quote,oose,innovative Informatik eG]
Typische Bestandteile eines Qualitätsszenarios sind Quelle, *Auslöser*, *Umgebung*, Artefakt, *Antwort*, Antwort-Maß

=== Generierung eines YouTube Videos
Ein Benutzer _(Auslöser)_ gibt dem ai-assistenten einen Text-Prompt zum Thema Klimawandel _(Umgebung)_. Der ai-assistent generiert eine Video zu diesem Thema, welches den eingegebenen Wünschen des Benutzers (Text-Prompt) entspricht _(Antwort)_ und eine zufriedenstellende Qualität für den Benutzer darstellt.
Dieses Ziel muss Benutzerunabhängig, maximal nach 10 Generierungversuchen der Fall sein. _(Antwort-Maß)_

=== Spracheingabe in Text umwandeln
Ein Benutzer _(Auslöser)_ nutzt die TTS- Funktion des ai-assistent und spricht durch ein durchschnittlich gutes Mikrofon in durchschnittlich gutem Deutsch und im korrekten Abstand zum Mikrofon. Die Aufnahme wird nicht durch Hintergrundgeräusche beeinträchtigt. _(Umgebung)_ Das Textergebnis entspricht dem gesprochenen Text _(Antwort)_ . Minimale Abweichungen bei mehreren Sätzen sind erlaubt _(Antwort-Maß)_.