= Open Source Lösungen verwenden
:navtitle: Open Source

== Fragestellung
=== Was genau ist das Problem ?
Ein Ziel dieses Systems ist es, das es autark, ohne Internet und ohne fremde Dienste, nur mit Open Source Lösungen funktioniert. Da aktuell Open Source Alternativen noch nicht in allen Bereichen die Qualität bieten, welche Closed Source Alternativen bieten, wird befürchtet, dass eine zufriedenstellende Erstellungsqualität mit Open Source Lösungen alleine nicht erreicht werden kann.

=== Warum ist es für die Architektur relevant ?
Zentrale Bausteine des lumidora sind externe Open Source Projekte und Lösungen. Stellt sich zu einem späteren Zeitpunkt heraus, das einige, speziell der Chatbot, keine ausreichend gute Qualität liefern, wenn sie mit Open Source Lösungen umgesetzt werden, ist dies Projektentscheidend.

=== Welche Auswirkungen hat die Entscheidung ?
Sie ist Projektentscheidend, da die wichtigste Eigenschaft des lumidora ist, nützlichen, qualitativ hochwertigen Output für den Benutzer zu liefern.

== Einflussfaktoren
=== Welche Randbedingungen haben wir einzuhalten
Das Projekt soll nur auf Open Source Software beruhen und lokal, ohne Internet lauffähig sein.

=== Welche Qualitätsziele sind zu beachten
Hohe Ausgabequalität der generierten Inhalte

=== Welche Risiken sind betroffen
Das Risiko das die Ausgabequalität nicht ausreichend ist.

== Annahmen
=== Welche Annahmen haben wir getroffen
* Closed Source Alternativen sind aktuell in einigen Bereichen den Open Source Lösungen überlegen
* Wir gehen davon aus das sich das Blatt im Laufe der Zeit ändern wird und Open Source Lösungen mindestens zu den Closed Source Lösugen gleichwertig sind.

=== Welche Annahmen können vorab wie überprüft werden
Es ist möglich die einzelnen Sprachmodelle zu testen. Es gibt auch Vergleiche, die beispielsweise zeigen, dass das Closed Source Projekt ChatGPT 4 bis jetzt noch weit besser ist als vergleichbare Open Source Modelle.
Wir können nicht überprüfen ob in Zukunft Open Source Sprachmodelle mindestens gleichwertig sind.

=== Mit welchen neuen Risiken müssen wir rechnen
Nur das oben bereits ewähnte Risiko, das die Ausgabequalität nicht zufriedenstellend ist, weil Open Source Modelle nicht die Qualität erreichen wie vergleichbare Closed Source Modelle.

== Alternativen

=== Welche Lösungsoptionen ziehen wir in die nähere Auswahl ?

Wir konnten mehrere Lösungsoptionen identifizieren

* Verwenden von Closed Source Alternativen in den Bereichen, indem Open Source aktuell noch besser ist.
* Verwenden von Open Source Projekten auch wenn sie aktuell noch schlechter sind.
* Dauerhafter Einsatz von Closed Source Projekten, wenn diese für ein speziellen Bereich besser sind.

=== Wie bewerten wir jede einzelne ?


=== Welche Option schließen wir bewusst aus ?
Die letze Option fällt direkt weg, da sie gegen einer unser wichtigsten Grundsätze verstößt und wir keine Closed Source Produkte verwenden wollen und unser assistent offline laufen soll.
Bleiben die ersten beiden Optionen.

== Ergebnis
Wir nehmen immer Open Source Tools, auch wenn die Ausgabequalität aktuell noch schlechter ist als bei Closed Source Alternativen.

=== Wer hat die Entscheidung getroffen ?
Dominik Bruhn

=== Wie ist sie begründet ?
Aufwand vor Ausgabequalität, da das Projekt aktuell nur von einer Person gemacht wird.

=== Wann wurde entschieden ?
Am 02.11.2023