= Anforderungen
:navtitle: Funktional

https://docs.asciidoctor.org/asciidoc/latest/


In diesem Abschnitt geht es um die Anforderungen, welch lumidora erfüllen soll.

== Kernaufgabe des Systems

lumidora soll eine einfache und schnelle Verwendung von aktuellen Open Source AI Projekten ermöglichen.
Er soll die Fähigkeiten dieser Projekte bündeln und schlußendlich ein digitaler Assistent und Content Erzeuger
mithilfe dieser Tools werden. Er soll mindestens folgende Fähigkeiten haben

* Text to Speech
* Speech to Text
* Text to Image
* Audio to Movie
* Text 2 Image

== Kategorie des Systems

Es handelt sich um ein System, welches hauptsächlich auf künstlicher Intelligenz beruht.
Es soll nützliche Open Source AI Tools verknüpfen und dem Benutzer einen extremen Mehrwert bieten,
sowohl im privaten, wie auch im Beruflichen. Das Tool soll in der Lage sein, verschiedenste Arten von Kontent
möglichst autonom erzeugen zu können.


== Wesentliche Qualitätsanforderungen


== Stakeholder
Im weiten ist jeder Stakeholder, welcher sich von AI unterstützen lassen will.
Im engeren Sinne, sind die Stakeholer, welche mit AI Kontent jeglicher Art in jeglicher Medialen Ausprägung (Audio, Video, Schriftlich, Bildlich) erstellen möchten.

=== Mögliche Stakeholder
* Content Creator
* Jedermann der mit dem PC arbeitet


[,ruby]
----
puts 'Hello, World!'
----






This is version *{page-component-display-version}* of Module One in Component B.

== Page source

This page is sourced from [.path]_demo-component-b/docs/modules/module-one/pages/overview.adoc_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in Module One*, the xref syntax would be `\xref:overview.adoc[]`.

To create a cross reference *to this page from a page in the ROOT module of Component B*, the xref syntax would be `\xref:module-one:overview.adoc[]`.

=== Always target the latest version of this page

To create a cross reference *to the latest version of this page from a page in Component A*, the xref syntax would be `\xref:component-b:module-one:overview.adoc[]`.

=== Target a specific version of this page

To create a cross reference *to version 1.0 of this page from a page in Component A*, the xref syntax would be `\xref:1.0@component-b:module-one:overview.adoc[]`.

