= Anforderungen
:navtitle: Funktional

In diesem Abschnitt geht es um die Anforderungen, welch lumidora erfüllen soll.

== Kernaufgabe des Systems

lumidora soll eine einfache und schnelle Verwendung von aktuellen Open Source AI Projekten ermöglichen.
Er soll die Fähigkeiten dieser Projekte bündeln und schlußendlich ein digitaler Assistent und Content Erzeuger
mithilfe dieser Tools werden. Er soll mindestens folgende Fähigkeiten haben

* Text to Speech
* Speech to Text
* Text to Image
* Audio to Movie
* Text 2 Image

== Kategorie des Systems

Es handelt sich um ein System, welches hauptsächlich auf künstlicher Intelligenz beruht.
Es soll nützliche Open Source AI Tools verknüpfen und dem Benutzer einen extremen Mehrwert bieten,
sowohl im privaten, wie auch im Beruflichen. Das Tool soll in der Lage sein, verschiedenste Arten von Kontent
möglichst autonom erzeugen zu können.

== Stakeholder
Im weiten ist jeder Stakeholder, welcher sich von AI unterstützen lassen will.
Im engeren Sinne, sind die Stakeholer, welche mit AI Kontent jeglicher Art in jeglicher Medialen Ausprägung (Audio, Video, Schriftlich, Bildlich) erstellen möchten.

=== Mögliche Stakeholder
* Content Creator
* Softwareentwickler
* Benutzer der mit dem PC arbeitet