@startuml
!include ../partials/diagrams/plantuml-stdlib/C4-PlantUML/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Systemkontextdiagramm für lumidora

Person(benutzer, "User", "")
System(aiassistant, "lumidora", "Persönlicher Assistent auf Basis künstlicher Intelligenz")

Rel(benutzer, aiassistant, "verwendet")
@enduml