= Herzlich Willkommen
:navtitle: Herzlich Willkommen

Dies ist die automatische Startseite für die Version {page-component-display-version} von Komponente B.

Komponente B ist eine von zwei Dokumentationskomponenten in der Antora Demo. Die andere Dokumentationskomponente, Komponente A, kann über das Komponentenauswahlfeld (auch als Komponentenschublade bezeichnet) am unteren Rand des Menüs auf der linken Seite der Seite aufgerufen werden.

== Seitenquelle

Diese Seite stammt aus der AsciiDoc-Datei mit dem Namen [.path]index.adoc, die sich im Verzeichnis [.path]demo-component-b/docs/modules/ROOT/pages befindet.

=== Warum ist dies die Startseite von Komponente B?

Diese Seite wird automatisch als Startseite von Komponente B verwendet, weil sie im ROOT-Modul gespeichert ist und den Namen [.path]index.adoc trägt.

=== Warum ist dies die Startseite der Antora Demo-Website?

Diese Seite dient als Startseite für die Antora Demo-Website, da sie in der Playbook-Datei der Demo-Website, [.path]site.yml, als start_page der Website festgelegt ist.

== Verweisungssyntax, um auf diese Seite zu verweisen

Um einen Verweis auf diese Seite von einer anderen Seite im ROOT-Modul von Komponente B zu erstellen, lautet die Verweissyntax \xref:index.adoc[].

Um einen Verweis auf diese Seite von einer Seite im Modul One von Komponente B zu erstellen, lautet die Verweissyntax \xref:ROOT:index.adoc[].

=== Immer die neueste Version dieser Seite anvisieren

Um einen Verweis auf die neueste Version dieser Seite von einer Seite in Komponente A zu erstellen, lautet die Verweissyntax \xref:component-b::index.adoc[].

=== Eine bestimmte Version dieser Seite anvisieren

Um einen Verweis auf die Version 1.0 dieser Seite von einer Seite in Komponente A zu erstellen, lautet die Verweissyntax \xref:1.0@component-b::index.adoc[].