@startuml
!include ../../partials/diagrams/plantuml-stdlib/C4-PlantUML/C4_Deployment.puml

LAYOUT_WITH_LEGEND()

title Bausteindiagramm Funktional

Person(benutzer, "Benutzer", "")


System_Boundary(lumidora, "Lumidora") {
    Container(coordinator, "Koordinator", "lumidora-coordinator")
    Container(tts, "Text to Speech", "lumidora-tts")
    Container(stt, "Speech to Text", "lumidora-stt")
    Container(chatbot, "Chatbot", "lumidora-chatbot")
    Container(vgen, "Videogenerator", "lumidora-vgen")
}

Rel(benutzer, tts, "benutzt", "")
Rel(benutzer, stt, "benutzt", "")
Rel(benutzer, chatbot, "benutzt", "")
Rel(benutzer, vgen, "benutzt", "")

Rel(chatbot, coordinator, "benutzt", "")
Rel(tts, coordinator, "benutzt", "")
Rel(stt, coordinator, "benutzt", "")
Rel(vgen, coordinator, "benutzt", "")

@enduml
