@startuml
!include ../../partials/diagrams/plantuml-stdlib/C4-PlantUML/C4_Component.puml

LAYOUT_WITH_LEGEND()

title Bausteindiagramm

Person(benutzer, "User", "")

component "Lumidora" as lumidora {

    component "Webinterface" as webinterface
    component "Kafka" as kafka
    component "TTS" as tts
    component "STT" as stt
    component "Chatbot" as chatbot
    component "vgen" as vgen

    component "Console" as console

}

Rel(benutzer, webinterface, "benutzt", "")
Rel(webinterface, kafka, "benutzt", "")

Rel(chatbot, kafka, "benutzt", "")
Rel(tts, kafka, "benutzt", "")
Rel(stt, kafka, "benutzt", "")
Rel(vgen, kafka, "benutzt", "")

@enduml