@startuml
!include ../../partials/diagrams/plantuml-stdlib/C4-PlantUML/C4_Component.puml

LAYOUT_WITH_LEGEND()

title Bausteindiagramm Technisch

Person(benutzer, "User", "")

component "Lumidora" as lumidora {
    component "Webinterface" as webinterface
    component "coordinator" as coordinator
    component "TTS" as tts
    component "STT" as stt
    component "Chatbot" as chatbot
    component "vgen" as vgen
    () kafka
}

Rel(benutzer, webinterface, "https api", "async")
Rel(webinterface, coordinator, "sendet Auftrag", "https/async")

Rel(chatbot, kafka, "liest (chatbot)", "async")
Rel(tts, kafka, "liest/schreibt", "async")
Rel(stt, kafka, "liest/schreibt", "async")
Rel(vgen, kafka, "liest/schreibt", "async")
Rel(coordinator, kafka, "liest/schreibt", "async")

@enduml