:navtitle: Technisch
= Randbedingungen

== Technische Randbedingungen
In diesem Abschnitt geht es um die Randbedingunen, welch für die Anwendung lumidora gelten. Das Projekt soll nur auf Open Source Software beruhen und lokal, ohne Internet lauffähig sein.

=== Zielhardware
ddd

==== Prozessor, RAM
Da lumidora auch lokal laufen soll und ai Anwendungen hohe Hardwareanforderungen haben gibt es folgende Mindestanforderungen:

- Moderner CPU i9 9X
- NVidia Grafikkarte mit mindestens 8 GB Arbeitsspeicher
- Mindestens 16 GB Ram

lumidora wird auch auf weniger Hardware lauffähig sein, es wird jedoch davon abgeraten.

==== Netwerk und Firewalls
Besondere Randbedingungen für Netwerk und Firewall gelten nicht.

=== Softwarevorgaben
==== Betriebssystem
lumidora wird hauptsächlich für Linux entwickelt und soll schlussendlich in Docker-Containern lauffähig sein.

==== Datenbanken

Aktuell ist eine Zwischenspeicherung im ersten Iterationsschritt nicht angedacht. Vorstellbar ist dies aber in Zukunft um dem lumidora eine Art Gedächtnis zu verschaffen.

==== Middleware
Keine Middleware nötig

==== Frameworks
Es werden verschiedene Frameworks im Bereich AI zum Einsatz kommen. Ebenfalls werden mehrere Github Projekte inkludiert werden.

==== Proxies
Kein Proxy vorhanden

==== Caches
Kein Cache notwendig

==== Monitoringsystem
Auf ein Monitoringsystem kann zunächst verzichtet werden

==== Application Server
Ein Application Server wird zunähst nicht benötigt.

==== Webserver
Eine Benutzeroberfläche im Browser ist zunächst nicht angedacht. Daher wird zunächst kein Webserver benötigt.

==== ID-Managementsystem
Da es sich zunächst um eine Anwendung handelt, welche Lokal für einzelne Benutzer gedacht ist, wird zunächst keine Authentifizierung nötig sein.

=== Betriebliche Aspekte
==== On-Premise oder Cloud
Zunächst soll lumidora lokal lauffähig sein. Durch die Anforderung Dockerkompatibel zu sein, ist eine einfache On-Premise, bzw. Cloud Integration schnell möglich.

==== Online- oder Batchbetrieb
lumidora soll in Echtzeit mit dem Benutzer interagieren können, aber auch Aufgaben asynchron, bspl. über Nacht erledigen können. Daher soll sowhol ein Online, wie auch ein Batchbetrieb möglich sein.

==== Betriebskosten
Solange die Software lokal läuft, fallen keine Betriebskosten an, sondern lediglich die Initialen Hardwarekosten beim Kauf.

==== Verfügbarkeit / Support
Verfügbarkeit im Lokalen Umfeld nicht relevant. Wenn lumidora On-Premise oder in der Cloud betrieben werden soll, muss sich der jeweilige Betreiber darum kümmern.

==== Wartungsfenster
Keine Wartungsfenster notwendig.

==== Zugriffsmöglichkeiten
Folgende Zugriffsmöglichkeiten werden implementiert (Reihenfolge: Absteigend nach Wichtigkeit sortiert)::
* Programmatisch über Python
* Konsole
* Restschnittstelle
* Frontend Python
* Frontend Web

==== Konfigurationsmanagement
Ein Konfigurationsmanagement ist nicht notwendig.

=== Entwicklungsvorgaben
==== Programmiersprache
Der Kern wird in Python programmiert, da Python im AI Open Source Bereich die gängigste Programmiersprache ist. Für spätere Sekundärprogramme kann je nach Notwendigkeit auf andere Programmiersprachen ausgewichen werden.

==== Entwicklungsumgebung
Die Entwicklungsumgebung ist frei wählbar.

==== Protokolle, Buildserver, Buildpipeline
Keine Vorgaben.

==== GUI-Gestaltung
In Aktueller Iteration werden keine Vorgaben bzgl. GUI gemacht, da zunächst auf die Implementierung des Kerns fokus gelegt wird.
Ist die Entwicklung des Kerns weitgenug vorangeschritten, wird darüber nachgedacht.

==== API
Die Api soll eine einfache und lose Kopplung zwischen den einzelnen Kernmodulen gewährleisten. Eine einfacher Austausch und Integration anderer Komponenten soll einfach möglich sein.

==== Namenskonventionen, Programmierrichtlinien, Versionsverwaltung
Sehen wir in diesem Projekt als Designvorgabe und verlagern die genaue Definition ins Entwicklerteam.
Das Team soll, für alle beteiligten Entwicklern akzeptierte, Programmierrichtlinien für dieses Projekt iterativ erarbeiten.



