= Systemkontext
:navtitle: Systemkontext

Das nachfolgende Schaubild zeigt das Zusammenspiel von Lumidora mit der näheren Umwelt. Es ist eine Vogelperspektive und zeigt eine Gesamtübersicht der Verbindungen und Schnittstllen von und zu Lumidora. Lumidora wird als Blackbox gezeigt und erst in weiteren Diagrammen näher betrachtet.

_Notiz: Funktional mit UML-Klassendiagramm. Technisch mit Verteilungsdiagramm (Deployment Diagram)_

== Funktionaler Kontext

[options="header", cols="1,5"]
|===
|Entität| Beschreibung

| Normaler Benutzer
| Jeder Benutzer, welcher mit Hilfe von KI seine Arbeit mit dem Computer optimieren will.

| Kontentersteller
| Benutzer, welche mithilfe von Lumidora Kontent erstellen möchten. Zum Beispiel Youtuber, Influencer

| Softwareentwickler
| Softwareentwickler, welche mithilfe von Lumidora ihren Softwareentwicklungsprozess optimieren möchten.

| Lumidora
| Persönlicher Assistent auf Basis künstlicher Intelligenz

|===

[plantuml]
----
include::example$systemkontext/systemkontext-funktional.plantuml[]
----

== Technischer Kontext

[plantuml]
----
include::example$systemkontext/systemkontext-technisch.plantuml[]
----
