@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_WITH_LEGEND()

title Systemkontextdiagramm für lumidora

Person(benutzer, "User", "")
System(aiassistant, "lumidora", "Persönlicher Assistent auf Basis künstlicher Intelligenz")

Rel(benutzer, aiassistant, "verwendet")
@enduml