@startuml
!include ../../partials/diagrams/plantuml-stdlib/C4-PlantUML/C4_Component.puml

LAYOUT_WITH_LEGEND()

title Systemkontext Funktional "Was""

Person(benutzer, "Benutzer", "")
System(lumidora, "Lumidora", "Persönlicher Assistent auf Basis künstlicher Intelligenz")

Rel(benutzer, lumidora, "verwendet")

@enduml
