= Qualitätsanforderungen
:navtitle: Qualität

In diesem Abschnitt geht es um die Qualitätsanforderungen, welche an Lumidora gestellt werden. Um Qualitätsanforderungen strukturiert zu erheben, helfen uns Qualitätsmodelle. Ein weitverbreitetes Qualitätsmodell ist der ISO 25010-Standard.

== Qualitätsmerkmal

[quote,oose,innovative Informatik eG]
Qualitätsmerkmal - messbare, qualitätsbezogene Eigenschaften eines Systems.
Zum Beispiel Fehlertoleranz, Ressourcenverbrauch, usw.

== Top 3 Qualitätsmerkmale dieses Projektes
In diese Projekt legen wir unseren Fokus auf die folgenden 3 Qualitätsmerkmale:

. Zuverlässigkeit
. Stabilität und Fehlertoleranz
. Benutzbarkeit

[abstract]
--
Der ISO 25010 ist ein internationaler Standard, der Qualitätsmodelle und Qualitätsanforderungen für Softwareprodukte und -systeme definiert. Er definiert im wesentlichen 8 Qualitätsmerkmale: _Effizienz (Performance), Wartbarkeit, Benutzbarkeit, Kompatibilität, Zuverlässigkeit, Sicherheit, Funktionale Eignung, Übertragbarkeit_
--

== Qualitätsziel
Aus den 3 wichtigsten Qualitätsmerkmalen leiten sich die 3 wichtigsten  Qualitätsziele des Projektes ab.

[quote,oose,innovative Informatik eG]
Ein Qualitätsziel ist eine Anforderung bzgl. eines Qualitätsmerkmals _(Benutzbarkeit -> Erlernbarkeit)_ , auf höherem Abstrationsniveau. Zum Beispiel _"Das System muss für die Angestellten unserer Personalabteilung leicht erlernbar sein."_

== Top 3 Qualitätsziele dieses Projektes

. Lumidora muss eine hohe Ein- und Ausgabequalität liefern. _(Zuverlässigkeit->Ausgereiftheit)_
. Lumidora muss Arbeitsaufträge die gestellt wurden erledigen können. _(Stabilität und Fehlertoleranz)_
. Benutzerfreundliche Verwendung der einzelnen Generierungsmodule.
Der Benutzer kann möglichst flexibel Inhalte generieren und die einzelnen Module von Lumidora ansprechen. _(Benutzbarkeit)_

[abstract]
--
Ein Qualitätsziel kann mehrere Qualitätszenarien beinhalten
--


=== Qualitätsszenarien

[quote,oose,innovative Informatik eG]
Ein Qualitätsszenario beschreibt, wie sich das System, wenn es gut implementiert wurde, auf bestimmte Impulse reagiert. Die Reaktion ist mess- oder beobachtbar und macht ein Qualitätsmerkmal des Systems für die Akteure (siehe Systemkontext) oder andere Stakeholder erlebbar.

[quote,oose,innovative Informatik eG]
Typische Bestandteile eines Qualitätsszenarios sind Quelle, *Auslöser*, *Umgebung*, Artefakt, *Antwort*, Antwort-Maß


==== Lumidora muss eine hohe Ein- und Ausgabequalität liefern.
. `Generierung eines YouTube Videos:`
Ein Benutzer _(Auslöser)_ gibt dem ai-assistenten einen Text-Prompt zum Thema Klimawandel . _(Umgebung)_ Der ai-assistent generiert eine Video zu diesem Thema, welches den eingegebenen Wünschen des Benutzers (Text-Prompt) entspricht_ und eine zufriedenstellende Qualität für den Benutzer darstellt. _(Antwort)
Dieses Ziel muss Benutzerunabhängig, maximal nach 10 Generierungversuchen der Fall sein. _(Antwort-Maß)_

. `Spracheingabe in Text umwandeln:`
Ein Benutzer _(Auslöser)_ nutzt die TTS- Funktion des ai-assistent und spricht durch ein durchschnittlich gutes Mikrofon in durchschnittlich gutem Deutsch und mit korrektem Abstand zum Mikrofon. Die Aufnahme wird nicht durch Hintergrundgeräusche beeinträchtigt. _(Umgebung)_ Das Textergebnis entspricht dem gesprochenen Text _(Antwort)_ . Minimale Abweichungen bei mehreren Sätzen sind erlaubt _(Antwort-Maß)_.