
= Qualitätsszenarien

[quote,oose,innovative Informatik eG]
Ein Qualitätsszenario beschreibt, wie sich das System, wenn es gut implementiert wurde, auf bestimmte Impulse reagiert. Die Reaktion ist mess- oder beobachtbar und macht ein Qualitätsmerkmal des Systems für die Akteure (siehe Systemkontext) oder andere Stakeholder erlebbar.


[quote,oose,innovative Informatik eG]
Typische Bestandteile eines Qualitätsszenarios sind Quelle, *Auslöser*, *Umgebung*, Artefakt, *Antwort*, Antwort-Maß

== Generierung eines YouTube Videos
Ein Benutzer _(Auslöser)_ gibt dem ai-assistenten einen Text-Prompt zum Thema Klimawandel . _(Umgebung)_ Der ai-assistent generiert eine Video zu diesem Thema, welches den eingegebenen Wünschen des Benutzers (Text-Prompt) entspricht_ und eine zufriedenstellende Qualität für den Benutzer darstellt. _(Antwort)
Dieses Ziel muss Benutzerunabhängig, maximal nach 10 Generierungversuchen der Fall sein. _(Antwort-Maß)_

== Spracheingabe in Text umwandeln
Ein Benutzer _(Auslöser)_ nutzt die TTS- Funktion des ai-assistent und spricht durch ein durchschnittlich gutes Mikrofon in durchschnittlich gutem Deutsch und mit korrektem Abstand zum Mikrofon. Die Aufnahme wird nicht durch Hintergrundgeräusche beeinträchtigt. _(Umgebung)_ Das Textergebnis entspricht dem gesprochenen Text _(Antwort)_ . Minimale Abweichungen bei mehreren Sätzen sind erlaubt _(Antwort-Maß)_.